---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: account-service-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/el-boukhari/argocdmicroservices.git
    targetRevision: HEAD
    path: Account-service
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-service-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/el-boukhari/argocdmicroservices.git
    targetRevision: HEAD
    path: config-service
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

# Repeat for other services
