apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service-container
          image: elboukhariyoucef/accountservice:1.0.0
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: configmaps-account-service
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
